### ISSUE TITLE
Splitting messages doesn't work with longer messages

### ISSUE THREAD

**Issue by zetok** [lehitoskin/blight#25]
Blight doesn't send larger messages in full.
Tested with newest Blight, Venom and µTox. Tested only in direction: Blight → other client. I didn't test sending between Blights.

Test sample: https://gist.github.com/zetok/53f0b55b21fcc25769a3

Steps to reproduce:
1. Copy and paste test sample as whole message and send it.
2. Receiver doesn't get whole message.

Reproducible: Always

**Comment by lehitoskin** [comment]
This was fixed a long time ago (circa 0bac7c153634e47336f00e26a966084894470c8f).
