### ISSUE TITLE
M$ Windows build

### ISSUE THREAD

**Issue by 4DA** [lehitoskin/blight#52]
How can we make one?

I've noticed that windows builds of tox have single libtox.dll, whereas linux ones do have libtoxcore.so and libtoxav.so

how can we handle this?

**Comment by lehitoskin** [comment]
@4DA @Halfwake We don't have a Windows VPS setup at the moment, but I do have the ability to manually generate (and sign) builds for amd64 machines. They'll be listed under "Releases" when I make new ones, but they'll be less frequent than build-on-commit. Maybe once a week? Possibly less, if I get lazy :P

**Comment by Halfwake** [comment]
"It either says it's not a valid library or the functions aren't included." Are the library and the Racket implementation both x64 or x86? I've had similar problems where that was the solution.
