### ISSUE TITLE
blight crashes/terminates(?) directly after startup - problem with pulseaudio?

### ISSUE THREAD

**Issue by holgersson32644** [lehitoskin/blight#62]
Hey,

I built at ~amd64 gentoo via the tox overlay ebuild (currently masked, but builds properly).
```
holgersson @ host % blight
#t
'ok
Blight: Connecting to DHT ... Connected!
AL lib: (EE) alc_cleanup: 1 device not closed
```
is the exact output. To me this looks like some sound trouble.

I'm running pulseaudio 6.0 with USE="X alsa alsa-plugin asyncns bluetooth caps dbus gdbm glib ipv6 orc qt4 ssl systemd tcpd udev webrtc-aec -doc -equalizer -gnome -gtk -jack -libsamplerate -lirc -native-headset -neon -ofono-headset -oss -realtime -selinux -system-wide -test -xen -zeroconf".

If you need more information and/or testings just tell (and/or contact me anywhere here, via e-mail or via IRC (holgersson; freenode).

Greetings,
holgersson

PS: I'd like to unmask blight now inside the overlay, but I'd like this issue fixed before, so other users can simply enjoy blight ;)

[Edit: Fixed code output - I forgot markdown was used here.]

**Comment by lehitoskin** [comment]
Blight doesn't depend on pulseaudio for anything. What version of media-sound/openal do you have installed?

**Comment by holgersson32644** [comment]
I just guessed pulseaudio claiming the device or something like this would cause this problem, therefor my info about pa.
Here is =media-libs/openal-1.1.6::gentoo with USE="alsa pulseaudio qt4 -coreaudio -debug -neon -oss -portaudio" installed.

**Comment by lehitoskin** [comment]
I'm using the older version on both of those. I'll install and check it out.

**Comment by holgersson32644** [comment]
I downgraded to media-sound/pulseaudio-5.0-r7 and media-libs/openal-1.15.1-r2 and rebuilt blight plus dependencies afterwards. The issue remains.

**Comment by lehitoskin** [comment]
I upgraded both packages and I still don't have any problems. What a conundrum...

**Comment by holgersson32644** [comment]
Do you use this ebuild or another one for blight? https://github.com/urras/gentoo-overlay-tox/blob/master/net-im/blight/blight-9999.ebuild

**Comment by lehitoskin** [comment]
I'm running it straight from the source. There's no code difference between that and what's installed from the ebuild.

**Comment by lehitoskin** [comment]
My USE flags are "X doc futures jit places threads -minimal". I think those are the default.

**Comment by holgersson32644** [comment]
Sorry, didn't find the time to test then, but blight builds and runs fine here anyways. I removed the mask in my fork an request for pulling it into the "main" tree ;-)
